config/routes.rb
Rails.application.routes.draw do
  root 'dogs#index'
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    Dog.create(dog_params)
    redirect_to root_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :description, :age, :breed)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/dogs/index.html.erb
<% @dogs.each do |dog| %>
  <div class="booyah-box">
    <h1><%= dog.name %></h1><br />
    <i><%= dog.age %></i><br />
    <i><%= dog.breed %></i><br />
    <p><%= dog.description %></p><br />
  </div>

  <hr />
<% end %>

app/views/dogs/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Dog Details</h1>
    <%= simple_form_for @dog do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :breed %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Add', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'DogPile', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_dog_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Dog
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>